# This is a basic workflow to deploy all discipline directories
# to a server via ssh/scp

name: deploy-all-disciplines

# Controls when the workflow will run
on:
  # Triggers the workflow on push for the "main" branch
  # hier muss noch der "main" branch von einem direkten commit geschützt werden
  # https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule
  push:
    branches: [ "main" ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
         since_last_remote_commit: true
         files: "discipline*"
         separator: ","
         
      - name: Anything changed
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          echo "List all the files that have changed: ${{ steps.changed-files.outputs.all_changed_files }}"
          
      - name: Upload to server
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.PRIVATE_KEY_PEM }}
          port: ${{ secrets.DEPLOY_PORT }}
          source: ${{ steps.changed-files.outputs.all_changed_files }}
          target: "~/"
